name: lint-python-code

on:
  pull_request:
    branches: [main]
    paths: ['**.py',  '**.ipynb']
  workflow_call:

jobs:
  python-linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repo
      uses: actions/checkout@v4.1.0

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install flake8
        pip install pynblint

    - name: Lint Python Code
      run: |
        flake8 . --select=E901,E999,F821,F822,F823 --exclude=__init__.py
      env:
        FLAKE8_OPTIONS: "--ignore=E203,W503"

    - name: Getting PR details
      run: |
        touch pr.json
        gh pr view $PR_NUMBER --json files > pr.json
        touch pr.json
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Linting all Jupyter Notebook files
      uses: jannekem/run-python-script-action@v1.6
      with:
        script: |
          import os
          import json
          with open('pr.json','r') as json_file:
            data = json.load(json_file)
            for file in data["files"]:
              path = file["path"]
              if os.path.exists(path):
                os.system(f"pynblint {path}")
